$('.l1').on('click',function(){
	$('.bd').hide();
	$('.qj').show();
	 if($('body').height()>$('.qj').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})
$('.l2').on('click',function(){
	$('.bd').hide();
	$('.hym').show();
	   if($('body').height()>$('.hym').height())
        		{
        			$('.bottom').attr('class','foot');
        		}
        		else{
        			$('.foot').attr('class','bottom');
        		}
})

$('.l3').on('click',function(){
	$('.bd').hide();
	$('.ft').show();
	if($('body').height()>$('.ft').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
        	
})

$('.l4').on('click',function(){
	$('.bd').hide();
	$('.sj').show();
	 if($('body').height()>$('.sj').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})

$('.l5').on('click',function(){
	$('.bd').hide();
	$('.zsxy').show();
	  if($('body').height()>$('.zsxy').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})

$('.l6').on('click',function(){
	$('.bd').hide();
	$('.sspm').show();
	  if($('body').height()>$('.sspm').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})
$('.l7').on('click',function(){
	$('.bd').hide();
	$('.hpsp').show();
	  if($('body').height()>$('.hpsp').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})
$('.l8').on('click',function(){
	$('.bd').hide();
	$('.qtspal').show();
	  if($('body').height()>$('.qtspal').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})
$('.l9').on('click',function(){
	$('.bd').hide();
	$('.hxyy').show();
	  if($('body').height()>$('.hxyy').height())
        		{
        			$('.bottom').attr('class','foot');
        		}else{
        			$('.foot').attr('class','bottom');
        		}
})
$('.fanh').on('click',function(){
	$($($(this).parent()).parent()).parent().hide();
	$('.bd').show();
})

